# SPDX-FileCopyrightText: 2026 Hari Srinivasan <harisrini21@gmail.com>
# SPDX-License-Identifier: Apache-2.0

"""Lock file generation with integrity hashes for agent versions."""

import hashlib
from datetime import UTC, datetime

import yaml
from loguru import logger as optic


def compute_integrity_hash(content: str) -> str:
    """Compute sha256 integrity hash for lock file entries."""
    optic.trace("computing integrity hash for {} bytes of content", len(content))
    digest = hashlib.sha256(content.encode()).hexdigest()
    return f"sha256-{digest}"


def generate_lock_file(
    resolved_components: list[dict],
    agent: str | None = None,
    agent_version: str | None = None,
) -> str:
    """Generate observal-agent.lock YAML content with integrity hashes.

    Args:
        resolved_components: list of dicts with keys:
            - type: str (mcp, skill, hook, prompt, sandbox)
            - name: str
            - resolved: str (version string)
            - id: str (component UUID)
            - source_sha: str | None (for external components)
            - content: str | None (for inline components - used to compute integrity)
        agent: str | None (agent name or identifier)
        agent_version: str | None (agent version string)

    Returns:
        YAML string for observal-agent.lock
    """
    optic.trace("generating lock file with {} resolved components", len(resolved_components))
    entries = []
    for comp in resolved_components:
        entry = {
            "type": comp["type"],
            "name": comp["name"],
            "resolved": comp["resolved"],
            "id": comp["id"],
        }
        if comp.get("source_sha"):
            entry["source_sha"] = comp["source_sha"]
        if comp.get("content"):
            entry["integrity"] = compute_integrity_hash(comp["content"])
        entries.append(entry)

    lock_data: dict = {
        "lock_version": 1,
    }
    if isinstance(agent, str) and agent:
        lock_data["agent"] = agent
    if isinstance(agent_version, str) and agent_version:
        lock_data["agent_version"] = agent_version
    lock_data["resolved_at"] = datetime.now(UTC).isoformat()
    lock_data["components"] = entries

    header = "# Auto-generated by observal agent release - do not edit manually\n"
    return header + yaml.safe_dump(lock_data, default_flow_style=False, sort_keys=False, allow_unicode=True)
